INSERT INTO gu (code, name) VALUES (27110, '대구광역시 중구');
INSERT INTO gu (code, name) VALUES (27140, '대구광역시 동구');
INSERT INTO gu (code, name) VALUES (27170, '대구광역시 서구');
INSERT INTO gu (code, name) VALUES (27200, '대구광역시 남구');
INSERT INTO gu (code, name) VALUES (27230, '대구광역시 북구');
INSERT INTO gu (code, name) VALUES (27260, '대구광역시 수성구');
INSERT INTO gu (code, name) VALUES (27290, '대구광역시 달서구');
INSERT INTO gu (code, name) VALUES (27710, '대구광역시 달성군');
INSERT INTO gu (code, name) VALUES (27720, '대구광역시 군위군');