package org.sherlockhomes.homes.batch.domain

class AptTrade(
    val sgg: String? = "-",
    val si: String? = "-",
    val gu: String? = "-",
    val dong: String? = "-",
    val aptDong: String? = null,
    val aptNm: String? = "-",
    val aptSeq: String? = "-",
    val bonbun: String? = "-",
    val bubun: String? = "-",
    val buildYear: Int? = 0,
    val buyerGbn: String? = null,
    val cdealDay: String? = null,
    val cdealType: String? = null,
    val dealAmount: String? = "-",
    val dealDay: String? = "-",
    val dealMonth: String? = "-",
    val dealYear: String? = "-",
    val dealingGbn: String? = null,
    val estateAgentSggNm: String? = null,
    val excluUseAr: String? = "-",
    val floor: String? = "-",
    val jibun: String? = "-",
    val landCd: String? = "-",
    val landLeaseholdGbn: String? = "-",
    val rgstDate: String? = "-",
    val roadNm: String? = "-",
    val roadNmBonbun: String? = "-",
    val roadNmBubun: String? = "-",
    val roadNmCd: Int? = 0,
    val roadNmSeq: String? = "-",
    val roadNmSggCd: Int? = 0,
    val roadNmbCd: Int? = 0,
    val sggCd: Int? = 0,
    val slerGbn: String? = "-",
    val umdCd: Int? = 0,
    val umdNm: String? = "-",
)