networks:
  map-network:
    driver: bridge
  user-network:
    driver: bridge
  apt-network:
    driver: bridge
  mono-network:
    driver: bridge

services:
  legal-dong:
    container_name: legal-dong
    image: mysql:8.0.30
    volumes:
      - ./db/legalDong/conf.d:/etc/mysql/conf.d
      - ./db/legalDong/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=map
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - map-network
  user:
    container_name: user
    image: mysql:8.0.30
    volumes:
      - ./db/user/conf.d:/etc/mysql/conf.d
      - ./db/user/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - user-network
  apt:
    container_name: apt
    image: mysql:8.0.30
    volumes:
      - ./db/apt/conf.d:/etc/mysql/conf.d
      - ./db/apt/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=apt
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - apt-network
  apt-replica:
    container_name: apt-replica
    image: mysql:8.0.30
    volumes:
      - ./db/apt-replica/conf.d:/etc/mysql/conf.d
      - ./db/apt-replica/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3318:3306"
    environment:
      - MYSQL_DATABASE=apt-replica
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - apt-network
  mono:
    container_name: mono
    image: mysql:8.0.30
    volumes:
      - ./db/mono/conf.d:/etc/mysql/conf.d
      - ./db/mono/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=mono
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - mono-network
  mono-replica:
    container_name: mono-replica
    image: mysql:8.0.30
    volumes:
      - ./db/mono-replica/conf.d:/etc/mysql/conf.d
      - ./db/mono-replica/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3319:3306"
    environment:
      - MYSQL_DATABASE=mono-replica
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - mono-network
  #  Batch
  meta:
    container_name: meta
    image: mysql:8.0.30
    volumes:
      - ./db/meta/conf.d:/etc/mysql/conf.d
      - ./db/meta/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3318:3318"
    environment:
      - MYSQL_DATABASE=meta
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
