networks:
  homes-network:
    driver: bridge
  user-network:
    driver: bridge
  apt-network:
    driver: bridge
services:
  legal-dong:
    container_name: legal-dong
    image: mysql:8.0.30
    volumes:
      - ./db/legalDong/conf.d:/etc/mysql/conf.d
      - ./db/legalDong/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=map
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - homes-network
  user:
    container_name: user
    image: mysql:8.0.30
    volumes:
      - ./db/user/conf.d:/etc/mysql/conf.d
      - ./db/user/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - user-network
  apt:
    container_name: apt
    image: mysql:8.0.30
    volumes:
      - ./db/apt/conf.d:/etc/mysql/conf.d
      - ./db/apt/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=apt
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - apt-network